experiment:
  regime: Open-Vocab
  category: order-symmetry

path:
  dset_dir: Dataset/
  mpi_log_dir: checkpoint/log/
  mpi_ckpt_dir: checkpoint/mpis/

dataset:
  dset: ocean_15
  start: null
  end: null

template:
  prompt: mpi-style
  description: non-index
  index: null
  desc:
    "+": mpi
    "-": mpi
  ans_type: desc # For open-vocab regime, this should always agree with {index}

shuffle:
  order: original
  shuffle_both: False

model:
  family: GPT2
  version: gpt2-large
  access_method: hf

params:
  max_tokens: 100
  top_p: 0.95
  temperature: 0.10
