---
experiment:
  regime: Constraint
  category: order-symmetry

path:
  dset_dir: Dataset/
  mpi_log_dir: checkpoint/log/
  mpi_ckpt_dir: checkpoint/mpis/

dataset:
  dset: ocean_988
  start:
  end:
template:
  prompt: mpi-style
  description: non-index
  index:
  desc:
    "+": mpi
    "-": mpi
  ans_type: desc # For open-vocab regime, this should always agree with {index}

shuffle:
  order: order-III
  shuffle_both: false

model:
  family: BART
  version: facebook/bart-base
  access_method: hf

algorithm:
  ll_type: ans_inv_perp

