---
experiment:
  regime: Open-Vocab
  category: order-symmetry

path:
  dset_dir: Dataset/
  mpi_log_dir: checkpoint/log/
  mpi_ckpt_dir: checkpoint/mpis/

dataset:
  dset: ocean_15
  start:
  end:

template:
  prompt: mpi-bart
  description: non-index
  index:
  desc:
    "+": mpi
    "-": mpi
  ans_type: desc # For open-vocab regime, this should always agree with {index}

shuffle:
  order: order-III
  shuffle_both: false

model:
  family: BART
  version: facebook/bart-large-cnn
  access_method: hf

params:
  max_tokens: 100
  top_p: 0.95
  temperature: 0.10
