experiment:
  regime: Constraint
  category: calibration

path:
  tmp_dir: template/candidates
  log_dir: checkpoint/log/
  ckpt_dir: checkpoint/mpis/

template:
  description: index
  index:
    "+": letter
    "-": letter
  desc:
    "+": mpi
    "-": mpi
  ans_type: index

shuffle:
  shuffle_both: false

algorithm:
  ll_type: ans_inv_perp
