path:
  dset_dir: Dataset/
  mpi_log_dir: checkpoint/log/BERT-Base/
  mpi_ckpt_dir: checkpoint/mpis/BERT-Base/

dataset:
  dset: ocean_120
  start: null
  end: null

template:
  prompt: mpi-style
  description: non-idx
  index: null
  desc:
    "+": mpi
    "-": mpi
  ans_type: desc

shuffle:
  order: original
  shuffle_both: False

model:
  family: BERT
  version: bert-base-uncased

algorithm:
  ll_type: ans_inv_perp
