path:
  dset_dir: Dataset/
  mpi_log_dir: checkpoint/log/
  mpi_ckpt_dir: checkpoint/mpis/

dataset: 
  dset: mpi_small
  start: null
  end: null

template:
  prompt: mpi-style
  description: desc-only
  option: 
    '+': desc-only
    '-': desc-only
  answer: 
    '+': desc-only
    '-': desc-only

shuffle: 
  status: False
  identifier: null # Usually Monte Carlo number

model:
  family: BERT
  version: bert-base-uncased

algorithm:
  ll_type: ans_inv_perp

