path:
  dset_dir: Dataset/
  mpi_log_dir: checkpoint/log/BERT-Base/order/
  mpi_ckpt_dir: checkpoint/mpis/BERT-Base/order/

dataset: 
  dset: ocean_988
  start: null
  end: null

template:
  prompt: mpi-style
  description: letter-desc
  option: 
    '+': letter-desc
    '-': letter-desc
  answer: 
    '+': letter-desc
    '-': letter-desc

shuffle: 
  status: True
  identifier: 0 # Usually Monte Carlo ID
  seed: 10000

model:
  family: BERT
  version: bert-base-uncased

algorithm:
  ll_type: ans_inv_perp

