path:
  dset_dir: Dataset/
  mpi_log_dir: checkpoint/log/BERT-Base/order/
  mpi_ckpt_dir: checkpoint/mpis/BERT-Base/order/

dataset:
  dset: ocean_988
  start: null
  end: null

template:
  prompt: mpi-style
  description: non-index
  index: null
  desc:
    "+": mpi
    "-": mpi
  ans_type: index-desc

shuffle:
  order: order-II
  shuffle_both: False

model:
  family: BERT
  version: bert-base-uncased

algorithm:
  ll_type: ans_inv_perp
