---
experiment:
  regime: Open-Vocab
  category: order-symmetry

path:
  dset_dir: Dataset/
  mpi_log_dir: checkpoint/log/
  mpi_ckpt_dir: checkpoint/mpis/

dataset:
  dset: ocean_988
  start:
  end:

template:
  prompt: mpi-gptneo
  description: syntactically-index
  index:
    "+": letter
    "-": letter
  desc:
    "+": mpi
    "-": mpi
  ans_type: index-desc

shuffle:
  order: original
  shuffle_both: false

model:
  family: GPTNEO
  # version: EleutherAI/gpt-neo-1.3B
  version: EleutherAI/gpt-neo-2.7B
  access_method: hf

params:
  max_tokens: 10
  top_p: 0.95
  temperature: 0.10
