---
experiment:
  regime: Constraint
  category: order-symmetry

path:
  dset_dir: Dataset/
  mpi_log_dir: checkpoint/log/
  mpi_ckpt_dir: checkpoint/mpis/

dataset:
  dset: ocean_988
  start:
  end:

template:
  # best: [og]-[s]-[type-ii]-[ans-i] 
  # worst: [og]-[s]-[type-iii]-[ans-iii]
  prompt: "[og]-[s]-[type-ii]-[ans-i]"
  description: index
  index:
    "+": letter
    "-": letter
  # index:
  desc:
    "+": mpi
    "-": mpi
  # ans_type: index-desc
  ans_type: desc
  is_lower_case: False

shuffle:
  order: order-III
  shuffle_both: false

# use opt for testing purpose
model:
  family: GPT2
  version: gpt2-large
  access_method: hf
  half_precision: false

algorithm:
  ll_type: ans_inv_perp
