experiment:
  regime: Open-Vocab
  category: order-symmetry

path:
  dset_dir: Dataset/
  mpi_log_dir: checkpoint/log/
  mpi_ckpt_dir: checkpoint/mpis/

dataset:
  dset: ocean_15
  start: null
  end: null

template:
  prompt: mpi-style-revised
  description: non-index
  index:
    "+": letter
    "-": letter
  desc:
    "+": mpi
    "-": mpi
  ans_type: index-desc # For open-vocab regime, this should always agree with {index}

shuffle:
  order: reverse
  shuffle_both: False

model:
  family: GPT3
  version: text-davinci-002
  access_method: api

params:
  max_tokens: 100
  top_p: 0.95
  temperature: 0.10
