experiment:
  regime: Open-Vocab
  category: order-symmetry

path:
  dset_dir: Dataset/
  mpi_log_dir: checkpoint/log/
  mpi_ckpt_dir: checkpoint/mpis/

dataset:
  dset: ocean_120
  start: null
  end: null

template:
  prompt: mpi-style
  description: non-index
  index: null
  desc:
    "+": mpi
    "-": mpi
  ans_type: desc

shuffle:
  order: original
  shuffle_both: False

model:
  family: GPT3
  version: text-davinci-002
  access_method: api

algorithm:
  ll_type: ans_inv_perp
