path:
  dset_dir: Dataset/
  mpi_log_dir: checkpoint/log/GPT/order/
  mpi_ckpt_dir: checkpoint/mpis/GPT/order/

dataset:
  dset: ocean_120
  start: null
  end: null

template:
  prompt: mpi-style
  description: non-index
  index: null
  desc:
    "+": mpi
    "-": mpi
  ans_type: desc

shuffle:
  order: reverse
  shuffle_both: False

model:
  family: GPT
  version: openai-gpt

algorithm:
  ll_type: ans_inv_perp
