---
experiment:
  regime: Constraint
  category: order-symmetry

path:
  dset_dir: Dataset/
  mpi_log_dir: checkpoint/log/
  mpi_ckpt_dir: checkpoint/mpis/

dataset:
  dset: ocean_988
  start:
  end:

template:
  # best: [lc]-[s]-[type-ii]-[ans-iii] 
  # worst: [lc]-[s]-[type-iii]-[ans-ii]
  prompt: "[og]-[s]-[type-ii]-[ans-iii]"
  description: non-index
  # index:
  #   "+": letter
  #   "-": letter
  index:
  desc:
    "+": mpi
    "-": mpi
  # ans_type: index-desc
  ans_type: desc
  is_lower_case: true

shuffle:
  order: order-III
  shuffle_both: false

# use opt for testing purpose
model:
  family: OPT
  version: facebook/opt-1.3b
  access_method: hf
  half_precision: false

algorithm:
  ll_type: ans_inv_perp
