path:
  dset_dir: Dataset/
  mpi_log_dir: checkpoint/log/GPT2-Medium/order/
  mpi_ckpt_dir: checkpoint/mpis/GPT2-Medium/order/

dataset:
  dset: ocean_120
  start: null
  end: null

template:
  prompt: mpi-style
  description: non-index
  index: null
  desc:
    "+": mpi
    "-": mpi
  ans_type: desc

shuffle:
  order: order-III
  shuffle_both: False

model:
  family: GPT2
  version: gpt2-medium

algorithm:
  ll_type: ans_inv_perp
