#!/bin/bash

sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job1.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job2.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job3.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job4.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job5.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job6.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job7.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job8.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job9.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job10.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job11.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job12.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job13.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job14.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job15.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job16.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job17.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job18.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job19.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job20.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job21.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job22.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job23.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job24.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job25.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job26.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job27.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job28.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job29.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job30.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job31.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job32.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job33.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job34.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job35.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job36.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job37.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job38.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job39.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job40.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job41.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job42.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job43.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job44.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job45.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job46.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job47.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job48.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job49.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job50.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job51.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job52.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job53.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job54.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job55.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job56.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job57.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job58.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job59.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job60.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job61.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job62.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job63.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job64.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job65.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job66.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job67.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job68.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job69.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job70.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job71.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job72.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job73.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job74.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job75.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job76.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job77.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job78.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job79.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job80.sbatch
