#!/bin/bash

sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job155.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job156.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job157.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job158.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job159.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job160.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job161.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job162.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job163.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job164.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job165.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job166.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job167.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job168.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job169.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job170.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job171.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job172.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job173.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job174.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job175.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job176.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job177.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job178.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job179.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job180.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job181.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job182.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job183.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job184.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job185.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job186.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job187.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job188.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job189.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job190.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job191.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job192.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job193.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job194.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job195.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job196.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job197.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job198.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job199.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job200.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job201.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job202.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job203.sbatch
sbatch /home/as14229/NYU_HPC/LLM-Personality-Codebase/jobs/sbatch/job204.sbatch
