path:
  dset_dir: Dataset/
  mpi_log_dir: checkpoint/log/BERT-Large/order/
  mpi_ckpt_dir: checkpoint/mpis/BERT-Large/order/

dataset:
  dset: ocean_988
  start: null
  end: null

template:
  prompt: mpi-style
  description: non-index
  index: null
  desc:
    "+": mpi
    "-": mpi
  ans_type: desc

shuffle:
  order: order-III
  shuffle_both: False

model:
  family: BERT
  version: bert-large-uncased

algorithm:
  ll_type: ans_inv_perp
