---
experiment:
  regime: Open-Vocab
  category: order-symmetry

path:
  dset_dir: Dataset/
  mpi_log_dir: checkpoint/MPI-results/
  mpi_ckpt_dir: checkpoint/MPI-results/

dataset:
  dset: ocean_988
  start:
  end:

template:
  prompt: mpi-naive
  description: syntactically-index
  index:
    "+": letter
    "-": letter
  desc:
    "+": mpi
    "-": mpi
  ans_type: index-desc # For open-vocab regime, this should always agree with {index}

shuffle:
  order: original
  shuffle_both: false

model:
  family: T0
  version: bigscience/T0pp
  access_method: hf

params:
  max_tokens: 100
  top_p: 0.95
  temperature: 0.10
