---
experiment:
  regime: Constraint
  category: order-symmetry

path:
  dset_dir: Dataset/
  mpi_log_dir: checkpoint/log/
  mpi_ckpt_dir: checkpoint/mpis/

dataset:
  dset: ocean_988
  start:
  end:

template:
  # best: [lc]-[ns]-[type-ii]-[ans-ii]
  # worst: [og]-[ns]-[type-ii]-[ans-ii]
  prompt: "[og]-[ns]-[type-ii]-[ans-ii]"
  description: non-index
  # index:
  #   "+": letter
  #   "-": letter
  index:
  desc:
    "+": mpi
    "-": mpi
  # ans_type: index-desc
  ans_type: desc
  is_lower_case: true

shuffle:
  order: order-III
  shuffle_both: false

# use opt for testing purpose
model:
  family: OPT
  version: facebook/opt-350m
  access_method: hf

algorithm:
  ll_type: ans_inv_perp
