experiment:
  regime: Constraint
  category: order-symmetry

path:
  dset_dir: Dataset/
  mpi_log_dir: checkpoint/log/
  mpi_ckpt_dir: checkpoint/mpis/

dataset:
  dset: ocean_988
  start: null
  end: null

template:
  prompt: mpi-style
  description: syntactic-letter
  index:
    "+": letter
    "-": letter
  desc:
    "+": mpi
    "-": mpi
  ans_type: index-desc

shuffle:
  order: order-II
  shuffle_both: False

model:
  family: BERT
  version: bert-base-uncased

algorithm:
  ll_type: ans_inv_perp
