---
experiment:
  regime: Constraint # this will be changed to type I or type II in the future if constraint
  category: template-selection

path:
  dset_dir: Dataset/
  mpi_log_dir: checkpoint/log/
  mpi_ckpt_dir: checkpoint/mpis/

dataset:
  dset: ocean_50
  start:
  end:
# This is the .yaml file for template selection
# So there are a bit different from the one used for MPI
template:
  description: non-index
  index: null
  desc:
    "+": mpi
    "-": mpi
  ans_type: desc

shuffle:
  order: original
  shuffle_both: False

# use opeai-gpt for testing purpose
model:
  family: GPTNEO
  version: EleutherAI/gpt-neo-2.7b
  access_method: hf
  half_precision: false

  # gpt-neo-125m , gpt-neo-1.3B , gpt-neo-2.7B

# parameters are needed for open vocab
params:
  max_tokens: 100
  top_p: 0.95
  temperature: 0.10

algorithm:
  ll_type: ans_inv_perp
