---
experiment:
  regime: Constraint # this will be changed to type I or type II in the future if constraint
  category: template-selection

path:
  dset_dir: Dataset/
  mpi_log_dir: checkpoint/log/
  mpi_ckpt_dir: checkpoint/mpis/

dataset:
  dset: ocean_120
  start: 0
  end: 3
# This is the .yaml file for template selection
# So there are a bit different from the one used for MPI
template:
  description: non-index
  index: null
  desc:
    "+": mpi
    "-": mpi
  ans_type: desc

shuffle:
  order: original
  shuffle_both: False

# use opeai-gpt for testing purpose
model:
  family: BERT
  version: bert-base-uncased
  access_method: hf

# parameters are needed for open vocab
params:
  max_tokens: 100
  top_p: 0.95
  temperature: 0.10

algorithm:
  ll_type: ans_inv_perp
