experiment:
  regime: Constraint
  category: order-symmetry

path:
  dset_dir: Dataset/
  mpi_log_dir: checkpoint/log/
  mpi_ckpt_dir: checkpoint/mpis/

dataset:
  dset: ocean_120
  start: null
  end: null

template:
  prompt: "[og]-[s]-[type-i]-[ans-i]"
  description: non-index
  # index:
  #   "+": letter
  #   "-": letter
  index: null
  desc:
    "+": mpi
    "-": mpi
  # ans_type: index-desc
  ans_type: desc
  is_lower_case: True

shuffle:
  order: original
  shuffle_both: False

# use opt for testing purpose
model:
  family: OPT
  version: facebook/opt-125m
  access_method: hf
  half_precision: false

algorithm:
  ll_type: ans_inv_perp
