experiment:
  regime: Constraint
  category: order-symmetry

path:
  dset_dir: Dataset/
  mpi_log_dir: checkpoint/log/
  mpi_ckpt_dir: checkpoint/mpis/

dataset:
  dset: ocean_988
  start: null
  end: null

template:
  prompt: mpi_type-i_space
  description: non-index
  index: null
  desc:
    "+": mpi
    "-": mpi
  ans_type: desc
  is_lower_case: True

shuffle:
  order: original
  shuffle_both: False

# use opeai-gpt for testing purpose
model:
  family: GPT
  version: openai-gpt
  access_method: hf

algorithm:
  ll_type: ans_inv_perp
