experiment:
  regime: Constraint
  category: order-symmetry #template-selection , order-symmetry

path:
  dset_dir: Dataset/
  mpi_log_dir: checkpoint/test/log/
  mpi_ckpt_dir: checkpoint/test/mpis/

dataset:
  dset: ocean_988
  start:
  end:

template:
  # [lc]-[ns]-[type-iii]-[ans-ii]
  prompt: "[og]-[ns]-[type-iii]-[ans-ii]"
  description: non-index-cali
  index:
    "+": letter
    "-": letter
  # index:
  desc:
    "+": mpi
    "-": mpi
  ans_type: index
  # ans_type: index-desc
  # ans_type: desc
  is_lower_case: True

shuffle:
  order: order-I
  shuffle_both: False

# use opt for testing purpose
model:
  # family: GPT2
  # version: gpt2
  family: OPT
  version: facebook/opt-125m
  access_method: hf
  half_precision: False

algorithm:
  ll_type: ans_inv_perp
