---
experiment:
  regime: Constraint
  category: order-symmetry

path:
  dset_dir: Dataset/
  mpi_log_dir: checkpoint/log/
  mpi_ckpt_dir: checkpoint/mpis/

dataset:
  dset: ocean_988
  start:
  end:

template:
  # best: [lc]-[ns]-[type-i]-[ans-iii] 
  # worst: [og]-[ns]-[type-iii]-[ans-iii] 
  prompt: "[og]-[ns]-[type-i]-[ans-iii]"
  description: non-index
  # index:
  #   "+": letter
  #   "-": letter
  index:
  desc:
    "+": mpi
    "-": mpi
  # ans_type: index-desc
  ans_type: desc
  # Best 
  is_lower_case: true


shuffle:
  order: order-III
  shuffle_both: false

# use opt for testing purpose
model:
  family: GPT2
  version: gpt2
  access_method: hf
  half_precision: false

algorithm:
  ll_type: ans_inv_perp
