---
experiment:
  regime: Constraint
  category: order-symmetry

path:
  dset_dir: Dataset/
  mpi_log_dir: checkpoint/log/
  mpi_ckpt_dir: checkpoint/mpis/

dataset:
  dset: ocean_988
  start:
  end:

template:
  # best: [lc]-[ns]-[type-i]-[ans-iii]
  # worst: [og]-[s]-[type-iii]-[ans-ii]
  prompt: "[og]-[s]-[type-iii]-[ans-ii]"
  description: non-index
  # index:
  #   "+": letter
  #   "-": letter
  index:
  desc:
    "+": mpi
    "-": mpi
  # ans_type: index-desc
  ans_type: desc
  is_lower_case: false

shuffle:
  order: original
  shuffle_both: false

# use opt for testing purpose
model:
  family: GPT2
  version: gpt2
  access_method: hf

algorithm:
  ll_type: ans_inv_perp
